# Generated by Django 5.0.7 on 2024-08-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0002_topic_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
